# Generated by Django 2.0.4 on 2018-09-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_propietario', models.DecimalField(decimal_places=2, max_digits=3)),
                ('incremento_segundo_anio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('interes_diario', models.DecimalField(decimal_places=4, max_digits=5)),
                ('email_direccion', models.EmailField(max_length=254)),
                ('email_asunto', models.CharField(max_length=150)),
                ('email_mensaje', models.TextField()),
                ('email_contrasenia', models.CharField(max_length=50)),
            ],
        ),
    ]
