# Generated by Django 2.0.4 on 2021-02-23 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '__first__'),
        ('propiedades', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoVario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('a_favor', models.BooleanField(default=False)),
                ('para_propietario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_mitad', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_primer_anio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_segundo_anio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_firma', models.DateField(default=None, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('garantes', models.ManyToManyField(related_name='_contrato_garantes_+', to='personas.Persona')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratos', to='personas.Inquilino')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratos', to='propiedades.Propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='MesContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_propietario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('api', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True)),
                ('expensas', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True)),
                ('agua', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True)),
                ('tasa', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True)),
                ('intereses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('varios_propietario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('varios_inquilino', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_pagado_propietario', models.DateField(default=None, null=True)),
                ('fecha_pagado_inquilino', models.DateField(default=None, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meses', to='contratos.Contrato')),
            ],
        ),
        migrations.AddField(
            model_name='conceptovario',
            name='mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='varios', to='contratos.MesContrato'),
        ),
    ]
