# Generated by Django 2.0.4 on 2021-02-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_mescontrato_expensas_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='oficina',
            field=models.CharField(choices=[('SAFE', 'Santa Fe'), ('ROSA', 'Rosario'), ('RECO', 'Reconquista')], default='SAFE', max_length=4),
        ),
    ]
