# Generated by Django 2.0.4 on 2021-03-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_contrato_oficina'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cobrar_agua_propietario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cobrar_api_propietariooo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cobrar_tasa_propietario',
            field=models.BooleanField(default=False),
        ),
    ]
