# Generated by Django 2.0.4 on 2021-03-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_auto_20210309_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cobrar_expensas_ext_propietario',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cobrar_expensas_propietario',
            field=models.BooleanField(default=False),
        ),
    ]
