# Generated by Django 2.0.4 on 2021-05-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_auto_20210323_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptovario',
            name='no_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cuotas_comision',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contrato',
            name='sellado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
