# Generated by Django 2.0.4 on 2018-09-03 22:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DNI')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=25)),
                ('direccion', models.CharField(blank=True, default='', max_length=254)),
                ('ciudad', models.CharField(blank=True, default='Santa Fe', max_length=50)),
                ('provincia', models.CharField(blank=True, default='Santa Fe', max_length=50)),
                ('nacionalidad', models.CharField(blank=True, default='Argentino/a', max_length=35)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personas.Persona')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personas.Persona')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
