# Generated by Django 2.0.4 on 2018-12-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=554),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(blank=True, default='Argentino/a', max_length=55),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=55),
        ),
    ]
